--小区配置及参数导出时延3天

--1.清除外部表
drop EXTERNAL table if EXISTS ext_edmp_cellinformation_${hiveconf:yyyyMMdd};
--2.创建外部表文件
$linux$touch /data1/load/yt_cellinformation_cell_${hiveconf:yyyyMMdd-3}.csv;
--3.创建外部表
CREATE WRITABLE EXTERNAL TABLE ext_edmp_cellinformation_${hiveconf:yyyyMMdd}(
		n1 varchar,n2 varchar,n3 varchar,n4 varchar,n5 varchar,n6 varchar,n7 varchar,n8 varchar,n9 varchar,n10 varchar,n11 varchar,n12 varchar,n13 varchar,n14 varchar,n15 varchar,n16 varchar,n17 varchar,n18 varchar,n19 varchar,n20 varchar,n21 varchar,n22 varchar,n23 varchar,n24 varchar,n25 varchar,n26 varchar,n27 varchar,n28 varchar,n29 varchar,n30 varchar,n31 varchar,n32 varchar,n33 varchar,n34 varchar,n35 varchar,n36 varchar,n37 varchar,n38 varchar,n39 varchar,n40 varchar,n41 varchar,n42 varchar,n43 varchar,n44 varchar,n45 varchar,n46 varchar,n47 varchar,n48 varchar,n49 varchar,n50 varchar,n51 varchar,n52 varchar,n53 varchar,n54 varchar,n55 varchar,n56 varchar,n57 varchar,n58 varchar,n59 varchar,n60 varchar,n61 varchar,n62 varchar,n63 varchar,n64 varchar,n65 varchar,n66 varchar,n67 varchar,n68 varchar,n69 varchar,n70 varchar,n71 varchar,n72 varchar,n73 varchar,n74 varchar,n75 varchar,n76 varchar,n77 varchar,n78 varchar,n79 varchar,n80 varchar,n81 varchar,n82 varchar,n83 varchar,n84 varchar,n85 varchar,n86 varchar,n87 varchar,n88 varchar,n89 varchar,n90 varchar,n91 varchar,n92 varchar,n93 varchar,n94 varchar,n95 varchar,n96 varchar,n97 varchar,n98 varchar,n99 varchar,n100 varchar,n101 varchar,n102 varchar,n103 varchar,n104 varchar,n105 varchar,n106 varchar,n107 varchar,n108 varchar,n109 varchar,n110 varchar,n111 varchar,n112 varchar,n113 varchar,n114 varchar,n115 varchar,n116 varchar,n117 varchar,n118 varchar,n119 varchar,n120 varchar,n121 varchar,n122 varchar,n123 varchar,n124 varchar,n125 varchar,n126 varchar,n127 varchar,n128 varchar,n129 varchar,n130 varchar,n131 varchar,n132 varchar,n133 varchar,n134 varchar,n135 varchar,n136 varchar,n137 varchar,n138 varchar,n139 varchar,n140 varchar,n141 varchar,n142 varchar,n143 varchar,n144 varchar,n145 varchar,n146 varchar,n147 varchar,n148 varchar,n149 varchar,n150 varchar,n151 varchar,n152 varchar,n153 varchar,n154 varchar,n155 varchar,n156 varchar,n157 varchar,n158 varchar,n159 varchar,n160 varchar,n161 varchar,n162 varchar,n163 varchar,n164 varchar,n165 varchar,n166 varchar,n167 varchar,n168 varchar,n169 varchar,n170 varchar,n171 varchar,n172 varchar,n173 varchar,n174 varchar,n175 varchar,n176 varchar,n177 varchar,n178 varchar,n179 varchar,n180 varchar,n181 varchar,n182 varchar,n183 varchar,n184 varchar,n185 varchar,n186 varchar,n187 varchar,n188 varchar,n189 varchar,n190 varchar,n191 varchar,n192 varchar,n193 varchar 
	) location ('gpfdist://192.168.36.120:8081/yt_cellinformation_cell_${hiveconf:yyyyMMdd-3}.csv') format 'csv' (delimiter '|' null '');
--4.写入数据
insert into ext_edmp_cellinformation_${hiveconf:yyyyMMdd} 
select 
t.intyear,
t.intmonth,
t.intday,
t.name,
t.vccgi, 
t.maximumtransmissionpower,
t.referencesignalpower,
t.pb,
t.vcPA,
t.eutrancell_id,
t.vczhNAME,
t.vcDnPrefix,
t.vendor_name,
t.vcManagedBy,
t.swversion,
t.administrativestate,
t.vcoperationalstate,
t.version,
t.vcManagementIpAddress,
t.vcHardwarePlatform,
t.patchinfo,
t3.vcvendorunitfamilytype ,
t3.vcvendorunittypenumber,
null,
t3.vcversionnumber,
t3.vcdateoflastservice,
t3.vcmanufacturerdata,
null,
null,
null,
t.enbid,
t.latitude,
t.longitude,
t3.vcfrequencyband,
t4.vctunableantennaidentification,
t4.vcAntEutranCellList,
t4.vcRetTiltValue,
t4.vcBearing,
t4.fHeight,
t4.fBaseElevation,
t4.vcHorizBeamwidth,
t4.vcVertBeamwidth,
t4.vcAntNumber,
t4.vcAntWeightParameter,
t.vcLocIpAddrList,
t.vcFarIpSubnetworkList,
t.celllocalid,
t.vcCELLSIZE,
t.plmnidlist,
t.tac,
t.pci,
t.relatedrrulist,
t.relatedantennalist,
t.bandindicator,
t.earfcn,
t.bandwidth,
t.sfassignment,
t.specialsfpatterns,
t.vcdrxswitch,
t.vcUeInactiveTimer,
t2.ConnMax_GD,
t.vcSupportActiveRRCNumbers,
t.vcUlCompSwitch,
t.vcDlCompSwitch,
t.vcUlMuMimoSwitch,
t.vcDlMuMimoSwitch,
t.vcUlIcicSwitch,
t.vcDlIcicSwitch,
t.vcUlFssSwitch,
t.vcDlFssSwitch,
t.vcHeaderCompressionSwitch,
t.vcSPSSwitchQCI1Ul,
t.vcCASwitchUl,
t.vcCASwitchDl,
t.vcTCI,
t.vcPci,
t.vcishoallowed,
t.vcislballowed,
t.plmnidlist,
null,
null,
t.vcAdjacentCellId,
t.vcBcchFrequency,
t.vcNCC,
t.vcBCC,
t.vcRAC,
t.vcGlobalUniqueMmeId,
t.vcSctpAssocLocalAddr,
t.vcSctpAssocRemoteAddr,
p1.CELLRESERVEDFOROPERATORUSE,
p1.CELLBARRED,
p1.ANTENNAPORTSCOUNT,
p1.PHICHRESOURCE,
p1.NRBCQI,
p1.NCSAN,
p1.N1PUCCHAN,
p1.ENABLE64QAM,
p1.N310,
p1.N311,
p1.T300,
p1.T301,
p1.T302,
p1.T304EUTRAN,
p1.T304GERAN,
p1.T310,
p1.T311,
p1.T320,
p1.SMEASURE,
p2.OFFSETFREQEUTRA,
p2.OFFSETFREQGERAN,
p2.A3OFFSETINTRAFCOV,
p2.A3HYSTERESISINTRAFCOV,
p2.A3TIMETOTRIGGERINTRAFCOV,
p2.A3MAXREPORTCELLSINTRAFCOV,
p2.A1THRESHOLDINTERFCOV,
p2.A1HYSTERESISINTERFCOV,
p2.A1TIMETOTRIGGERINTERFCOV,
p2.A1REPORTQUANTITYINTERFCOV,
p2.A2THRESHOLDINTERFCOV,
p2.A2HYSTERESISINTERFCOV,
p2.A2TIMETOTRIGGERINTERFCOV,
p2.A2REPORTQUANTITYINTERFCOV,
p2.A3OFFSETINTERFCOV,
p3.A3HYSTERESISINTERFCOV,
p3.A3TIMETOTRIGGERINTERFCOV,
p3.A3MAXREPORTCELLSINTERFCOV,
p3.A4THRESHOLDINTERFCOV,
p3.A4HYSTERESISINTERFCOV,
p3.A4TIMETOTRIGGERINTERFCOV,
p3.A4MAXREPORTCELLSINTERFCOV,
p3.A5THRESHOLD1INTERFCOV,
p3.A5THRESHOLD2INTERFCOV,
p3.A5HYSTERESISINTERFCOV,
p3.A5TIMETOTRIGGERINTERFCOV,
p3.A5MAXREPORTCELLSINTERFCOV,
p4.A1THRESHOLDGERANCOV,
p4.A1HYSTERESISGERANCOV,
p4.A1TIMETOTRIGGERGERANCOV,
p4.A1MAXREPORTCELLSGERANCOV,
p4.A2THRESHOLDGERANCOV,
p4.A2HYSTERESISGERANCOV,
p5.A2TIMETOTRIGGERGERANCOV,
p5.A2MAXREPORTCELLSGERANCOV,
p5.B1THRESHOLDGERANCOV,
p5.B1HYSTERESISGERANCOV,
p5.B1TIMETOTRIGGERGERANCOV,
p5.B2THRESHOLD1GERANCOV,
p5.B2THRESHOLD2GERANCOV,
p5.B2HYSTERESISGERANCOV,
p5.B2TIMETOTRIGGERGERANCOV,
p5.A2THRESHOLDBLINDGERANCOV,
p6.A2HYSTERESISBLINDGERANCOV,
p6.A2TIMETOTRIGGERBLINDGERANCOV,
p6.A2MAXREPORTCELLSBLINDGERANCOV,
p6.BLINDHOFIRSTRAT,
p6.REDIRECTSWITCHGERAN,
p6.BLINDREDIRECTSWITCHGERAN,
p6.CSFBSWITCHGERAN,
p6.SRVCCSWITCHGERAN,
p1.INTRAFREQRESELECTION,
p1.QHYST,
p1.CELLRESELECTIONPRIORITY,
p1.CELLRESELECTIONPRIORITYRES,
p1.QRXLEVMINRESELECTION,
p1.PMAXRESELECTION,
p1.SINTRASEARCH,
p1.ALLOWEDMEASBANDWIDTH,
p1.SINTRASEARCHPR9,
p1.SINTRASEARCHQR9,
p1.QQUALMINR9RESELECTION,
p1.SNONINTRASEARCH,
p1.THRESHSERVINGLOW,
p1.SNONINTRASEARCHPR9,
p1.THRESHXHIGH,
p1.THRESHXLOW,
p1.QOFFSETFREQ,
p1.CELLRESELECTIONPRIORITYGERAN,
p1.QRXLEVMINGERAN,
p1.PMAXGERAN,
p1.THRESHXHIGHGERAN,
p1.THRESHXLOWGERAN,
p1.QRXLEVMIN,
p1.QRXLEVMINOFFSET,
p1.PMAX,
p1.PREAMBLEINITIALRECTARGETPOWER,
p1.PREAMBLETRANSMAX,
p1.RARESPONSEWINDOWSIZE,
p1.MACCONTENTIONRESOLUTIONTIMER,
p1.MAXHARQMSG3TX,
p2.ALPHA,
p2.P0NOMINALPUCCH
from 
(select * from yy_ltesource_cell_month where intdateid=${hiveconf:yyyyMMdd-3} and intpid=substr(${hiveconf:yyyyMMdd-3},0,7)) t
left join (select * from yy_lteperformance_cell_month where intdateid=${hiveconf:yyyyMMdd-3} and intpid=substr(${hiveconf:yyyyMMdd-3},0,7))t2 on t.vccgi=t2.vccgi
left join (select * from yy_ltesource_rru_month where intyear=substr(${hiveconf:yyyyMMdd-3},0,5) and intmonth=substr(${hiveconf:yyyyMMdd-3},5,2) and intday=${hiveconf:day}-3 and intpid=substr(${hiveconf:yyyyMMdd-3},0,7))t3 on t.vccgi=t3.vccgi
left join (select * from yy_ltesource_antennalte_month where intyear=substr(${hiveconf:yyyyMMdd-3},0,5) and intmonth=substr(${hiveconf:yyyyMMdd-3},5,2) and intday=${hiveconf:day}-3 and intpid=substr(${hiveconf:yyyyMMdd-3},0,7))t4 on t.vccgi=t4.vcvgi
left join (select * from yy_lteparameter_cell_part1_month where intyear=substr(${hiveconf:yyyyMMdd-3},0,5) and intmonth=substr(${hiveconf:yyyyMMdd-3},5,2) and intday=${hiveconf:day}-3 and intpid=substr(${hiveconf:yyyyMMdd-3},0,7))p1 on t.vccgi=p1.vccgi
left join (select * from yy_lteparameter_cell_part2_month where intyear=substr(${hiveconf:yyyyMMdd-3},0,5) and intmonth=substr(${hiveconf:yyyyMMdd-3},5,2) and intday=${hiveconf:day}-3 and intpid=substr(${hiveconf:yyyyMMdd-3},0,7))p2 on t.vccgi=p2.vccgi
left join (select * from yy_lteparameter_cell_part3_month where intyear=substr(${hiveconf:yyyyMMdd-3},0,5) and intmonth=substr(${hiveconf:yyyyMMdd-3},5,2) and intday=${hiveconf:day}-3 and intpid=substr(${hiveconf:yyyyMMdd-3},0,7))p3 on t.vccgi=p3.vccgi
left join (select * from yy_lteparameter_cell_part4_month where intyear=substr(${hiveconf:yyyyMMdd-3},0,5) and intmonth=substr(${hiveconf:yyyyMMdd-3},5,2) and intday=${hiveconf:day}-3 and intpid=substr(${hiveconf:yyyyMMdd-3},0,7))p4 on t.vccgi=p4.vccgi
left join (select * from yy_lteparameter_cell_part5_month where intyear=substr(${hiveconf:yyyyMMdd-3},0,5) and intmonth=substr(${hiveconf:yyyyMMdd-3},5,2) and intday=${hiveconf:day}-3 and intpid=substr(${hiveconf:yyyyMMdd-3},0,7))p5 on t.vccgi=p5.vccgi
left join (select * from yy_lteparameter_cell_part6_month where intyear=substr(${hiveconf:yyyyMMdd-3},0,5) and intmonth=substr(${hiveconf:yyyyMMdd-3},5,2) and intday=${hiveconf:day}-3 and intpid=substr(${hiveconf:yyyyMMdd-3},0,7))p6 on t.vccgi=p6.vccgi;
--5.删除外部表
drop EXTERNAL table if EXISTS ext_edmp_cellinformation_${hiveconf:yyyyMMdd};
--6.把导出文件移到指定目录
$linux$mv /data1/load/yt_cellinformation_cell_${hiveconf:yyyyMMdd-3}.csv /data1/ftp_data/yt_lte_cell_month/yt_cellinformation_cell_${hiveconf:yyyyMMdd-3}.csv;
--7.压缩文件，减少使用空间
$linux$gzip /data1/ftp_data/yt_lte_cell_month/yt_cellinformation_cell_${hiveconf:yyyyMMdd-3}.csv;
--8.文件天文件只保留14天，需要清除14天前的文件
$linux$rm -f /data1/ftp_data/yt_lte_cell_month/yt_cellinformation_cell_${hiveconf:yyyyMMdd-17}.csv;